apiVersion: v1
kind: Service
metadata:
  name: agentops-server-svc
  namespace: agentops
  labels:
    app.kubernetes.io/name: agentops-server
    app.kubernetes.io/component: api
spec:
  selector:
    app: agentops-server
  ports:
    - name: http
      port: 4000
      targetPort: http
  type: ClusterIP
